---
- name: "[NC-DL] - Unzip is installed"
  package: name=unzip state=installed

- block:
  - name: "Download & extract Nextcloud to /tmp."
    unarchive:
      copy: no
      src: "{{ nextcloud_full_url }}"
      dest: "/tmp/"

  - name: "[NC-DL] - Move extracted files to {{ nextcloud_webroot }}."
    command: "cp -r /tmp/nextcloud/. {{ nextcloud_webroot }}/"

  - name: "[NC-DL] - Remove nextcloud archive files"
    file: path=/tmp/nextcloud state=absent
