---
- set_fact: nextcloud_tls_cert_file="{{ nextcloud_tls_cert | default("/etc/ssl/" + nextcloud_instance_name + ".crt") }}"
- set_fact: nextcloud_tls_cert_key_file="{{ nextcloud_tls_cert_key | default("/etc/ssl/" + nextcloud_instance_name + ".key") }}"

- name: "[SIGNED TLS] - Certificat is on the host"
  copy:
    dest: "{{ nextcloud_tls_cert_file }}"
    src: "{{ nextcloud_tls_src_cert }}"

- name: "[SIGNED TLS] - Key is on the host"
  copy:
    dest: "{{ nextcloud_tls_cert_key_file }}"
    src: "{{ nextcloud_tls_src_cert_key }}"

- name: "[SIGNED TLS] - check TLS certicate permissions"
  file:
    path: "{{ nextcloud_tls_cert_file }}"
    mode: 0644
    group: "{{ websrv_group }}"

- name: "[SIGNED TLS] - check TLS key permissions"
  file:
    path: "{{ nextcloud_tls_cert_key_file }}"
    mode: 0640
    group: "{{ websrv_group }}"
